# /api/v3/values/schemas/{id}
---
get:
  parameters:
    - name: id
      in: path
      description: The identifier of the value. This is typically the value of the `property` property of the `Values` resource.
      example: 'startDate'
      required: true
      schema:
        type: String
  responses:
    '200':
      content:
        application/hal+json:
          schema:
            "$ref": "../components/schemas/schema_model.yml"
          examples:
            'Values::Property Start date schema':
              $ref: '../components/examples/values_property_schema.yml'
      description: OK
      headers: {}
    '404':
      content:
        application/hal+json:
          schema:
            $ref: '../components/schemas/error_response.yml'
          example:
            _type: Error
            errorIdentifier: urn:openproject-org:api:v3:errors:NotFound
            message: The requested resource could not be found.
      description: |-
        Returned if the schema does not exist.
  tags:
    - Values::Property
  description: The schema of a `Values` resource.
  operationId: View_values_schema
  summary: View Values schema
