name: opencode-sync
on:
  workflow_dispatch:
  schedule:
    - cron: '5 */1 * * *' # Every hour

permissions:
  contents: read # to fetch code (actions/checkout)
jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: webfactory/ssh-agent@v0.6.0
        with:
            ssh-private-key: ${{ secrets.OPENCODE_SYNC_SSH_PRIVATE_KEY }}
      - name: Mirror
        run: |
          export GIT_SSH_COMMAND="ssh -v -o StrictHostKeyChecking=no -o KexAlgorithms=ecdsa-sha2-nistp256"

          echo "Adding opencode remote"
          git remote add opencode git@gitlab.opencode.de:bmi/souveraener_arbeitsplatz/component-code/management/openproject/openproject-core.git

          echo "Pushing all refs"
          git push --tags --force --prune opencode "refs/remotes/origin/*:refs/heads/*"
